name: CI/CD Innovatech - DB

on:
  push:
    branches: [ "main" ]
    paths:
      - "db/**"

jobs:
  build-push-deploy-db:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build imagen DB
      run: |
        cd db
        docker build -t innovatechv1-db .

    - name: Tag imagen DB
      run: |
        docker tag innovatechv1-db:latest ${{ secrets.ECR_REPO_URL_DB }}:latest

    - name: Push imagen DB
      run: |
        docker push ${{ secrets.ECR_REPO_URL_DB }}:latest

    - name: Deploy DB EC2
      run: |
        aws ssm send-command \
          --instance-ids "${{ secrets.EC2_DB_INSTANCE_ID }}" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy innovatechv1-db" \
          --parameters '{
            "commands":[
              "set -e",
              "aws ecr get-login-password --region '${{ secrets.AWS_REGION }}' | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
              "docker pull ${{ secrets.ECR_REPO_URL_DB }}:latest",
              "docker stop innovatechv1-db || true",
              "docker rm innovatechv1-db || true",
              "docker run -d --name innovatechv1-db -p 3306:3306 -v mysql_data:/var/lib/mysql ${{ secrets.ECR_REPO_URL_DB }}:latest"
            ]
          }' \
          --output text